version: "2"

services:
  backend:
    image: lukealbarracin/campus-cache-backend:latest
    # platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
    env_file:
      - ./backend/.env

  frontend:
    image: lukealbarracin/campus-cache-frontend:latest
    # platform: linux/amd64  
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/campus-cache/src:/app/src
      - ./frontend/campus-cache/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    
  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
